name: Build and Deploy React v16.14.1 App to EC2 Tomcat 10.1.41

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.8]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show environment info
        run: |
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          echo "Disk Space:"
          df -h
          echo "Memory:"
          free -m

      - name: Give executable rights to react-scripts (if needed)
        run: chmod +x node_modules/.bin/react-scripts || true

      - name: Build React App and Capture Logs
        run: |
          echo "Starting React build..."
          CI=false npm run build 2>&1 | tee build.log
        continue-on-error: true

      - name: Check for Build Failures
        run: |
          if grep -q "Failed to compile" build.log || grep -q "Error:" build.log; then
            echo "❌ Build failed. Check the log above for details."
            exit 1
          else
            echo "✅ Build completed successfully."
          fi

      - name: Prepare SSH Key for EC2
        env:
          EC2_SSH_KEY: ${{secrets.EC2_SSH_KEY}}
        run: |
          echo "$EC2_SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
      - name: Manage QuaLISWeb Directory on EC2
        env:
          EC2_HOST: ${{secrets.EC2_HOST}}
          EC2_USER: ${{secrets.EC2_USERNAME}}
          TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
        run: |
          echo "EC2_USER=$EC2_USER"
          echo "EC2_HOST=$EC2_HOST"         
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            TARGET_DIR="$TOMCAT_WEBAPPS_PATH/QuaLISWeb"
            if [ -d "$TARGET_DIR" ]; then
              echo "Directory $TARGET_DIR exists. Deleting it..."
              rm -rf "$TARGET_DIR"
              echo "Error in Removing the directory $TARGET_DIR "
            else
              echo "Directory $TARGET_DIR does not exist."
            fi
            echo "Creating new directory $TARGET_DIR..."
            mkdir -p "$TARGET_DIR"
            chmod -R 755 "$TARGET_DIR"
            chown -R $EC2_USER:$EC2_USER "$TARGET_DIR"
          EOF

      - name: Deploy React App to EC2 Tomcat
        env:
          EC2_HOST: ${{secrets.EC2_HOST}}
          EC2_USER: ${{secrets.EC2_USERNAME}}
          TOMCAT_WEBAPPS_PATH: ${{secrets.TOMCAT_WEBAPPS_PATH}}
        run: |
          rsync -avz --delete -e "ssh -i ssh_key.pem -o StrictHostKeyChecking=no" ./build/ $EC2_USER@$EC2_HOST:$TOMCAT_WEBAPPS_PATH/QuaLISWeb/

      - name: Restart Tomcat on EC2
        env:
          EC2_HOST: ${{secrets.EC2_HOST}}
          EC2_USER: ${{secrets.EC2_USERNAME}}
        run: |
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "sudo systemctl restart tomcat"

      - name: Cleanup SSH Key
        run: rm -f ssh_key.pem
